source 'https://github.com/BigShow1949/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'FFAPIsKit_Example' do
  pod 'FFAPIsKit', :path => '../'

  target 'FFAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
